"""Auto-generate shell completion scripts from a live argparse parser.

Introspects the parser's action groups to build completion scripts
for bash and zsh — eliminating the need to maintain static completion
files that drift from the actual argparse definitions.

Usage:
    hermes_loop --completion-script bash   # print bash completion
    hermes_loop --completion-script zsh    # print zsh completion
    hermes_loop --completion-script bash | source /dev/stdin
"""

import os


def _classify_flags(parser):
    """Introspect parser and return (bool_flags, value_flags, choice_flags).

    bool_flags is a list of flag strings (--flag).
    value_flags is a list of flag strings (--flag).
    choice_flags is a dict: {flag: [choices]} -- subset of value_flags that have choices.
    """
    bool_flags = []
    value_flags = []
    choice_flags = {}

    seen = set()
    for group in parser._action_groups:
        title = group.title
        if title in ("positional arguments", "optional arguments", "options"):
            continue
        for action in group._group_actions:
            if not action.option_strings:
                continue
            flag = action.option_strings[0]
            if flag in seen:
                continue
            seen.add(flag)
            if flag in ("--help",):
                continue
            if action.nargs == 0 or (
                hasattr(action, "const") and action.const is not None
            ):
                bool_flags.append(flag)
            else:
                value_flags.append(flag)
                if action.choices:
                    choice_flags[flag] = list(action.choices)

    bool_flags.sort()
    value_flags.sort()
    return bool_flags, value_flags, choice_flags


def _esc(text):
    """Escape single quotes for shell script output."""
    return text.replace("'", "'\\''")


def _help_text(action):
    """Get the first sentence of help text, or a fallback."""
    h = (action.help or "").split(".")[0].strip()
    if not h:
        h = (action.help or "")[:60]
    return _esc(h)


def _find_help(parser, flag):
    """Find the help text for a flag by searching all parser action groups."""
    for group in parser._action_groups:
        for action in group._group_actions:
            if action.option_strings and action.option_strings[0] == flag:
                return _help_text(action)
    return ""


# -- File/dir completion flags -- classified once, used by both generators

_FILE_ARGS = frozenset(
    {
        "--context-file",
        "--goals-file",
        "--output-schema-file",
        "--log-file",
        "--status-file",
        "--status-html",
        "--save-config",
        "--config",
    }
)

_DIR_ARGS = frozenset(
    {
        "--archive-dir",
        "--watch-dir",
        "--workdir",
    }
)


# ---- Bash completion generator -----------------------------------------


def generate_bash_completion(parser):
    """Generate a complete bash completion script from the argparse parser."""
    bool_flags, value_flags, choice_flags = _classify_flags(parser)

    bool_str = "\n".join(f"        {flag}" for flag in bool_flags)
    value_str = "\n".join(f"        {flag}" for flag in value_flags)

    # Choice flag cases
    choice_cases = []
    for flag, choices in sorted(choice_flags.items()):
        choices_str = " ".join(choices)
        choice_cases.append(f"        {flag})")
        choice_cases.append(
            f'            COMPREPLY=($(compgen -W "{choices_str}" -- "$cur"))'
        )
        choice_cases.append("            return 0")
        choice_cases.append("            ;;")

    # Group value-only flags by type using pipe-delimited case patterns
    file_group = [f for f in value_flags if f in _FILE_ARGS]
    dir_group = [f for f in value_flags if f in _DIR_ARGS]
    choice_group_set = set(choice_flags.keys())
    value_only = [
        f
        for f in value_flags
        if f not in _FILE_ARGS and f not in _DIR_ARGS and f not in choice_group_set
    ]

    file_pattern = "|".join(f for f in file_group)
    dir_pattern = "|".join(f for f in dir_group)
    value_only_pattern = "|".join(f for f in value_only)

    return f"""\
#!/usr/bin/env bash
# Auto-generated bash completion for the infinite-loop daemon (hermes_loop)
# Generated by: --completion-script bash (introspects live argparse parser)
# Source: scripts/completion/bash (auto-generated -- do not edit manually)
#
# Provides completions for:
#   launch-loop.py
#   python3 launch-loop.py
#   python3 -m hermes_loop         (still supported as fallback)
#   run.sh
#   scripts/run-loop.sh

# ---------------------------------------------------------------------------
# Core completion function
# ---------------------------------------------------------------------------
_hermes_loop_completions()
{{
    local cur prev words cword split
    _init_completion -s || return

    # ---- ALL BOOLEAN (no-argument) flags ----
    local bool_flags=(
{bool_str}
    )

    # ---- ALL VALUE (argument-taking) flags ----
    local value_flags=(
{value_str}
    )

    # ---- Complete the value after a known value flag ----
    case "$prev" in
{chr(10).join(choice_cases)}\
{chr(10) + '        ' + file_pattern + ')' if file_pattern else ''}
            _filedir
            return 0
            ;;
{chr(10) + '        ' + dir_pattern + ')' if dir_pattern else ''}
            _filedir -d
            return 0
            ;;
{chr(10) + '        ' + value_only_pattern + ')' if value_only_pattern else ''}
            return 0
            ;;
    esac

    # ---- Offer flag completions ----
    local all_flags=("${{bool_flags[@]}}" "${{value_flags[@]}}")

    # Filter out flags that already appear on the command line
    local filtered=()
    local i flag
    for flag in "${{all_flags[@]}}"; do
        local already=0
        for ((i=0; i < ${{#words[@]}} - 1; i++)); do
            if [[ "${{words[$i]}}" == "$flag" ]]; then
                already=1
                break
            fi
        done
        if [[ $already -eq 0 ]]; then
            filtered+=("$flag")
        fi
    done

    if [[ "$cur" == --* ]] || [[ -z "$cur" ]]; then
        COMPREPLY=($(compgen -W "${{filtered[*]}}" -- "$cur"))
    else
        COMPREPLY=($(compgen -W "${{filtered[*]}}" -- "$cur"))
    fi

    return 0
}}

# ---------------------------------------------------------------------------
# Dispatcher -- checks the first words of the command line to decide whether
# we are completing for hermes-loop.
# ---------------------------------------------------------------------------
_hermes_loop_dispatch()
{{
    local cmd="${{1##*/}}"          # basename of the first command word

    # Direct completions for known entry points
    case "$cmd" in
        launch-loop.py|run.sh|run-loop.sh)
            _hermes_loop_completions
            return 0
            ;;
    esac

    # For "python3 <TAB>", check the full command line for our script names
    if [[ "$cmd" == "python3" || "$cmd" == "python" ]]; then
        local line="${{COMP_LINE:0:$COMP_POINT}}"
        # Match: python3 launch-loop.py ...   or
        #        python3 -m hermes_loop ...
        if [[ "$line" =~ python3\\ +launch-loop\\.py ]] || \\
           [[ "$line" =~ python3\\ +-m\\ +hermes_loop ]]; then
            _hermes_loop_completions
            return 0
        fi
    fi

    return 1
}}

# ---------------------------------------------------------------------------
# Register completions
# ---------------------------------------------------------------------------

# Direct commands
complete -F _hermes_loop_dispatch launch-loop.py
complete -F _hermes_loop_dispatch run.sh
complete -F _hermes_loop_dispatch scripts/run-loop.sh

# For python3, fall back to default completion when not completing for hermes-loop.
complete -o default -F _hermes_loop_dispatch python3
complete -o default -F _hermes_loop_dispatch python
"""


# ---- Zsh completion generator -------------------------------------------


def generate_zsh_completion(parser):
    """Generate a complete zsh completion script from the argparse parser."""
    bool_flags, value_flags, choice_flags = _classify_flags(parser)

    bool_lines = []
    for flag in bool_flags:
        desc = _find_help(parser, flag)
        bool_lines.append(f"    '{flag}[{desc}]'")

    value_lines = []
    for flag in value_flags:
        desc = _find_help(parser, flag)
        value_lines.append(f"    '{flag}:{desc}'")

    bool_joined = "\n".join(bool_lines)
    value_joined = "\n".join(value_lines)

    # Build choice-aware _arguments lines for flags with choices
    choice_extra = []
    for flag, choices in sorted(choice_flags.items()):
        flag_short = flag.lstrip("-").replace("-", "_")
        choices_str = " ".join(choices)
        choice_extra.append(f"        '{flag}:-:({choices_str})'")

    choice_extra_lines = "\n".join(choice_extra) if choice_extra else ""

    # Build state handler for choice flags
    choice_state_lines = []
    for flag, choices in sorted(choice_flags.items()):
        flag_short = flag.lstrip("-").replace("-", "_")
        desc = _find_help(parser, flag)
        choices_str = " ".join(choices)
        choice_state_lines.append(
            f"    {flag})\n"
            f'        _describe -t {flag_short} "{desc}" \\\n'
            f'          "({choices_str})"\n'
            f"        ;;\n"
        )
    # File and dir completion for certain flag values
    file_group = [f for f in value_flags if f in _FILE_ARGS]
    dir_group = [f for f in value_flags if f in _DIR_ARGS]

    file_val_flags = " ".join(f for f in file_group)
    dir_val_flags = " ".join(f for f in dir_group)

    return f"""\
#compdef launch-loop.py run.sh run-loop.sh python3

# Auto-generated zsh completion for the infinite-loop daemon (hermes_loop)
# Generated by: --completion-script zsh (introspects live argparse parser)
# Source: scripts/completion/zsh (auto-generated -- do not edit manually)
#
# Install: cp this file to /usr/share/zsh/site-functions/_hermes_loop
#    or:   mkdir -p ~/.zsh/completion && cp this ~/.zsh/completion/_hermes_loop
#          fpath=(~/.zsh/completion \\$fpath)
#          autoload -Uz compinit && compinit

# ---------------------------------------------------------------------------
# ALL BOOLEAN (no-argument) flags
# ---------------------------------------------------------------------------
local -a bool_flags
bool_flags=(
{bool_joined}
)

# ---------------------------------------------------------------------------
# ALL VALUE (argument-taking) flags
# ---------------------------------------------------------------------------
local -a value_flags
value_flags=(
{value_joined}
)

local -a file_val_flags=(
    {file_val_flags}
)

local -a dir_val_flags=(
    {dir_val_flags}
)

# ---------------------------------------------------------------------------
# Completion entry point
# ---------------------------------------------------------------------------
local curcontext="$curcontext" state line

_arguments -C \\
    "${{bool_flags[@]}}" \\
    "${{value_flags[@]}}" \\
    '*::arg:->args' \\
    && return 0

case $state in
    args)
        local curcontext="$curcontext" state line
        _arguments -C \\
{choice_extra_lines}\\
            '*::arg:->subargs'
        case $state in
            subargs)
                _files
                ;;
        esac
        ;;
esac

return 0
"""


# ---- In-place regeneration ----------------------------------------------


def regenerate_completion_files(base_dir, parser):
    """Regenerate the bash and zsh completion scripts in scripts/completion/."""

    comp_dir = os.path.join(base_dir, "scripts", "completion")
    os.makedirs(comp_dir, exist_ok=True)

    bash_path = os.path.join(comp_dir, "bash")
    zsh_path = os.path.join(comp_dir, "zsh")

    with open(bash_path, "w") as f:
        f.write(generate_bash_completion(parser))
    with open(zsh_path, "w") as f:
        f.write(generate_zsh_completion(parser))

    return bash_path, zsh_path
