"""
wizard — Interactive setup wizard for the Infinite Loop Daemon.

Guides first-time users through the most common configuration options
interactively, generating a .env file at the end. Drastically lowers
the onboarding barrier for users facing 90+ CLI flags.

Usage:
    hermes_loop --init       # walk through interactive setup
    hermes_loop --wizard     # alias for --init

The wizard asks about:
  1. Goal / goals-file
  2. Workers (parallelism)
  3. Git integration (git, git-commit, store-git-diff)
  4. Evolve mode
  5. Max iterations
  6. Convergence detection (auto-stop on stuck results)
  7. Model / Profile / Provider (spawned session overrides)
  8. Notifications (desktop, ntfy, pushbullet)
  9. Log file (persistent logging to disk)
  10. Toolsets (spawned session capabilities)
  11. Heartbeat timeout (session health monitoring)
  12. Quiet mode
  13. Output path for .env (default: ./.env)

At the end it writes the chosen settings to a .env file and shows
a summary of how to run.
"""

import os
import sys


def _ask(prompt: str, default: str = "") -> str:
    """Ask the user a question with an optional default value."""
    if default:
        full = f"{prompt} [{default}]: "
    else:
        full = f"{prompt}: "
    try:
        val = input(full).strip()
    except (EOFError, KeyboardInterrupt):
        print()
        return default or ""
    if not val:
        return default
    return val


def _ask_yesno(prompt: str, default: bool = False) -> bool:
    """Ask a yes/no question. Returns True for y/yes, False for n/no."""
    hint = "y/N" if not default else "Y/n"
    full = f"{prompt} [{hint}]: "
    try:
        val = input(full).strip().lower()
    except (EOFError, KeyboardInterrupt):
        print()
        return default
    if not val:
        return default
    return val in ("y", "yes", "yeah", "yep", "sure", "ok")


def _print_header() -> None:
    """Print the wizard banner."""
    print()
    print("  ═══════════════════════════════════════════════════════")
    print("   Infinite Loop Daemon — Interactive Setup Wizard")
    print("  ═══════════════════════════════════════════════════════")
    print()
    print("  This wizard will ask you a few questions and generate")
    print("  a .env file so you can run the daemon with zero CLI flags.")
    print()
    print("  Press Ctrl+C at any time to cancel. Defaults are shown")
    print("  in brackets [] — just press Enter to accept them.")
    print()


def _print_summary(env_lines: list[str]) -> None:
    """Print a summary of the configuration chosen."""
    from .config import LAUNCH_LOOP_VERSION

    print()
    print("  ═══════════════════════════════════════════════════════")
    print(f"   Configuration Summary (v{LAUNCH_LOOP_VERSION})")
    print("  ═══════════════════════════════════════════════════════")
    print()
    for line in env_lines:
        if line.startswith("#"):
            continue
        if "=" in line:
            key, val = line.split("=", 1)
            val = val.strip('"')
            if val:
                # Present boolean flags as --flag for readability
                if val.lower() == "true":
                    flag = key.replace("INFINITE_LOOP_", "").lower().replace("_", "-")
                    print(f"    --{flag}")
                else:
                    print(f"    {key} = {val}")
    print()


def _save_env(path: str, lines: list[str]) -> bool:
    """Write the .env file, preserving existing content for non-INFINITE_LOOP_ vars."""
    # Read existing .env to preserve non-daemon vars
    existing_lines: list[str] = []
    if os.path.isfile(path):
        with open(path) as f:
            for line in f:
                stripped = line.strip()
                if stripped and not stripped.startswith("#") and "=" in stripped:
                    key = stripped.split("=", 1)[0].strip()
                    if key.startswith("INFINITE_LOOP_"):
                        continue  # will be overwritten
                existing_lines.append(line)

    try:
        with open(path, "w") as f:
            for line in existing_lines:
                f.write(line)
            if existing_lines and not existing_lines[-1].endswith("\n"):
                f.write("\n")
            if existing_lines:
                f.write("\n")
            f.write("# ── Generated by wizard --init ──────────────────────────\n")
            f.write(f"# Run: bash run.sh\n")
            f.write(f"# Generated: see --init or --wizard flag\n")
            f.write("# ────────────────────────────────────────────────────────\n")
            for line in lines:
                f.write(line + "\n")
        return True
    except OSError as e:
        print(f"\n  [ERROR] Could not write {path}: {e}")
        return False


def run_wizard() -> None:
    """Run the interactive setup wizard."""
    _print_header()

    env_lines: list[str] = []

    # ── Step 1: Goal ────────────────────────────────────────────────
    print("  ── Step 1: Goal ───────────────────────────────────────")
    goal = _ask("  What task should the loop work on?", "")
    goals_file = ""
    if not goal:
        goals_file = _ask(
            "  Path to a goals file (one goal per line, or leave empty)",
            "",
        )
    if not goal and not goals_file:
        print("  [WARN] No goal or goals file specified. You'll need to pass")
        print("         --goal or --goals-file when running.")
    print()

    # ── Step 2: Workers ─────────────────────────────────────────────
    print("  ── Step 2: Parallelism ────────────────────────────────")
    workers_str = _ask("  Number of parallel workers", "1")
    try:
        workers = int(workers_str)
        if workers < 1:
            workers = 1
    except ValueError:
        workers = 1
    print()

    # ── Step 3: Git ─────────────────────────────────────────────────
    print("  ── Step 3: Git Integration ────────────────────────────")
    git_desc = (
        "  Capture git diff stats per iteration? " "(tracks file changes, line counts)"
    )
    use_git = _ask_yesno(git_desc, False)
    git_commit = False
    store_git_diff = False
    if use_git:
        git_commit = _ask_yesno("  Auto-commit changes per iteration?", False)
        store_git_diff = _ask_yesno(
            "  Store full git diff in the ledger (for review)?", False
        )
    print()

    # ── Step 4: Evolve ──────────────────────────────────────────────
    print("  ── Step 4: Evolution ──────────────────────────────────")
    evolve = _ask_yesno(
        "  Let iterations propose the next goal (self-directing)?", False
    )
    print()

    # ── Step 5: Max iterations ──────────────────────────────────────
    print("  ── Step 5: Iteration Limit ────────────────────────────")
    max_iter_str = _ask(
        "  Max iterations (0 = infinite, 10 = stop after 10)",
        "0",
    )
    try:
        max_iter = int(max_iter_str)
        if max_iter < 0:
            max_iter = 0
    except ValueError:
        max_iter = 0
    print()

    # ── Step 6: Convergence Detection ───────────────────────────────
    print("  ── Step 6: Convergence Detection ───────────────────────")
    print("  Convergence detection stops the loop when iterations")
    print("  produce very similar summaries (stuck detection).")
    convergence_stop = _ask_yesno(
        "  Auto-stop when iterations stop making progress?",
        False,
    )
    threshold = 0.9
    window = 5
    if convergence_stop:
        print()
        print("  Convergence compares word-overlap similarity across")
        print("  recent iterations. Higher = more restrictive.")
        threshold_str = _ask(
            "  Similarity threshold (0.6=moderate, 0.9=strict, default 0.9)",
            "0.9",
        )
        try:
            threshold = float(threshold_str)
            if threshold < 0.0:
                threshold = 0.9
            elif threshold > 1.0:
                threshold = 1.0
        except ValueError:
            threshold = 0.9
        window_str = _ask(
            "  How many recent iterations to compare (default 5)",
            "5",
        )
        try:
            window = int(window_str)
            if window < 2:
                window = 5
        except ValueError:
            window = 5
    print()

    # ── Step 7: Model / Profile / Provider ──────────────────────────
    print("  ── Step 7: Model & Profile (advanced) ─────────────────")
    print("  These override the Hermes model/profile/provider used")
    print("  in spawned sessions. Leave empty to use defaults.")
    print()
    model = _ask("  Model override (e.g., 'anthropic/claude-sonnet-4')", "")
    profile = _ask("  Profile name (e.g., 'work')", "")
    provider = _ask("  Provider override (e.g., 'openrouter')", "")
    print()

    # ── Step 8: Notifications ───────────────────────────────────────
    print("  ── Step 8: Notifications ──────────────────────────────")
    notify_desktop = _ask_yesno("  Desktop notifications (Linux notify-send)?", False)
    notify_ntfy = ""
    if _ask_yesno("  Push notifications via ntfy.sh?", False):
        notify_ntfy = _ask("  ntfy topic name (e.g., 'my-loop-alerts')", "")
    notify_pushbullet = ""
    if _ask_yesno("  Push notifications via Pushbullet?", False):
        notify_pushbullet = _ask(
            "  Pushbullet API access token",
            "",
        )
    print()

    # ── Step 9: Log file ────────────────────────────────────────────
    print("  ── Step 9: Logging ────────────────────────────────────")
    log_file = _ask(
        "  Path to persistent log file (leave empty for stdout only)",
        "",
    )
    log_max_mb = 10
    if log_file:
        log_max_mb_str = _ask("  Max log file size in MB before rotation", "10")
        try:
            log_max_mb = int(log_max_mb_str)
            if log_max_mb < 1:
                log_max_mb = 10
        except ValueError:
            log_max_mb = 10
    print()

    # ── Step 10: Toolsets ───────────────────────────────────────────
    print("  ── Step 10: Toolsets (advanced) ──────────────────────")
    print("  Toolsets control what tools spawned Hermes sessions")
    print("  have access to. The defaults are good for most users.")
    print()
    custom_toolsets = _ask_yesno("  Customize spawned session toolsets?", False)
    toolsets_str = ""
    if custom_toolsets:
        print()
        print("  Available toolsets:")
        print("    terminal, file, web, delegation, skills, browser,")
        print("    memory, session_search, code_execution, todo, vision,")
        print("    search, image_gen, video, computer_use")
        print()
        toolsets_str = _ask(
            "  Comma-separated toolsets",
            "terminal,file,delegation,web,skills,browser,memory,session_search,code_execution,todo,vision",
        )
    print()

    # ── Step 11: Heartbeat timeout ──────────────────────────────────
    print("  ── Step 11: Session Health (advanced) ─────────────────")
    print("  Heartbeat monitoring detects hung/frozen sessions")
    print("  and automatically retries them.")
    print()
    use_heartbeat = _ask_yesno(
        "  Enable heartbeat-based session health monitoring?", False
    )
    hb_timeout = 0
    if use_heartbeat:
        hb_str = _ask(
            "  Seconds of inactivity before a session is considered hung",
            "120",
        )
        try:
            hb_timeout = int(hb_str)
            if hb_timeout < 10:
                hb_timeout = 120
        except ValueError:
            hb_timeout = 120
    print()

    # ── Step 12: Quiet mode ─────────────────────────────────────────
    print("  ── Step 12: Output Style ─────────────────────────────")
    quiet = _ask_yesno(
        "  Quiet mode (compact output, ideal for background daemons)?",
        False,
    )
    print()

    # ── Step 13: Output path ────────────────────────────────────────
    print("  ── Step 13: Save ─────────────────────────────────────")
    default_env = os.path.join(os.getcwd(), ".env")
    env_path = _ask("  Path to save .env file", default_env)
    if not env_path:
        env_path = default_env
    print()

    # ── Build env lines ─────────────────────────────────────────────
    if goal:
        env_lines.append(f'INFINITE_LOOP_GOAL="{goal}"')
    if goals_file:
        env_lines.append(f'INFINITE_LOOP_GOALS_FILE="{goals_file}"')
    if workers != 1:
        env_lines.append(f"INFINITE_LOOP_WORKERS={workers}")
    if use_git:
        env_lines.append("INFINITE_LOOP_GIT=true")
    if git_commit:
        env_lines.append("INFINITE_LOOP_GIT_COMMIT=true")
    if store_git_diff:
        env_lines.append("INFINITE_LOOP_STORE_GIT_DIFF=true")
    if evolve:
        env_lines.append("INFINITE_LOOP_EVOLVE=true")
    if max_iter > 0:
        env_lines.append(f"INFINITE_LOOP_MAX_ITERATIONS={max_iter}")
    if convergence_stop:
        env_lines.append("INFINITE_LOOP_CONVERGENCE_STOP=true")
        env_lines.append(f"INFINITE_LOOP_CONVERGENCE_THRESHOLD={threshold}")
        env_lines.append(f"INFINITE_LOOP_CONVERGENCE_WINDOW={window}")
    if model:
        env_lines.append(f'INFINITE_LOOP_MODEL="{model}"')
    if profile:
        env_lines.append(f'INFINITE_LOOP_PROFILE="{profile}"')
    if provider:
        env_lines.append(f'INFINITE_LOOP_PROVIDER="{provider}"')
    if notify_desktop:
        env_lines.append("INFINITE_LOOP_NOTIFY_DESKTOP=true")
    if notify_ntfy:
        env_lines.append(f'INFINITE_LOOP_NOTIFY_NTFY="{notify_ntfy}"')
    if notify_pushbullet:
        env_lines.append(f'INFINITE_LOOP_NOTIFY_PUSHBULLET="{notify_pushbullet}"')
    if log_file:
        env_lines.append(f'INFINITE_LOOP_LOG_FILE="{log_file}"')
        if log_max_mb != 10:
            env_lines.append(f"INFINITE_LOOP_LOG_MAX_MB={log_max_mb}")
    if toolsets_str:
        env_lines.append(f'INFINITE_LOOP_TOOLSETS="{toolsets_str}"')
    if hb_timeout > 0:
        env_lines.append(f"INFINITE_LOOP_HEARTBEAT_TIMEOUT={hb_timeout}")
    if quiet:
        env_lines.append("INFINITE_LOOP_QUIET=true")

    # ── Always add INFINITE_LOOP_RUN so bash run.sh works ────────────
    env_lines.append("INFINITE_LOOP_RUN=true")

    # ── Summary & save ──────────────────────────────────────────────
    _print_summary(env_lines)

    save = False
    if env_lines:
        save = _ask_yesno(f"  Write these settings to {env_path}?", True)
        if save:
            if _save_env(env_path, env_lines):
                print(f"  [OK] Configuration saved to {env_path}")
            else:
                print("  [FAIL] Could not write configuration file.")
        else:
            # Print instructions instead
            print()
            print("  To use these settings, pass them as CLI flags:")
            print()
            print("    hermes_loop \\")
            for line in env_lines:
                if line.startswith("INFINITE_LOOP_RUN="):
                    continue  # skip --run, added automatically
                key, val = line.split("=", 1)
                flag = key.replace("INFINITE_LOOP_", "").lower()
                val_clean = val.strip('"')
                if val_clean.lower() == "true":
                    print(f"      --{flag} \\")
                else:
                    # Convert INFINITE_LOOP_ flag names to CLI flag equivalents
                    cli_flag = flag
                    if "_" in cli_flag:
                        cli_flag = cli_flag.replace("_", "-")
                    print(f"      --{cli_flag} {val_clean} \\")
            print("      --run")
            print()
    else:
        print("  [INFO] No configuration to save (all defaults).")
        print()

    # ── Next steps ──────────────────────────────────────────────────
    print("  ── Next Steps ────────────────────────────────────────────")
    print()
    print("  To start the daemon with your configuration:")
    print()
    if env_lines and save:
        print("    bash run.sh")
        print("    # or: make run")
    else:
        print("    hermes_loop --goal '<your goal>' --run")
    print()
    print("  To check the current status:")
    print("    hermes_loop --status")
    print()
    print("  To stop the daemon:")
    print("    echo 'stop' > /tmp/infinite-loop-stop")
    print()
    print("  For help:")
    print("    hermes_loop --help")
    print("    hermes_loop --examples")
    print("    hermes_loop --explain <flag>")
    print("    make help")
    print()

    # ── Readiness check ───────────────────────────────────────────
    _run_readiness_check(env_lines)


def _run_readiness_check(env_lines: list[str]) -> None:
    """Run lightweight readiness checks after wizard completes.

    Verifies that key dependencies and paths referenced in the
    wizard configuration are actually available. Reports each
    check with a pass/warn/fail icon. Does NOT exit on failure
    — the user can fix issues and re-run.
    """
    print("  ── Readiness Check ────────────────────────────────")
    print()

    checks: list[tuple[str, bool | None, str]] = []

    # Parse the env lines into a dict
    env: dict[str, str] = {}
    for line in env_lines:
        if "=" in line:
            key, val = line.split("=", 1)
            env[key.strip()] = val.strip().strip('"')

    # Check 1: hermes binary
    import shutil

    hermes_found = shutil.which("hermes")
    if hermes_found:
        checks.append(("hermes binary on PATH", True, hermes_found))
    else:
        checks.append(
            (
                "hermes binary on PATH",
                None,
                "Not found - install Hermes Agent first (hermes setup)",
            )
        )

    # Check 2: workdir (if specified)
    workdir = env.get("INFINITE_LOOP_WORKDIR", "")
    if workdir:
        workdir = os.path.expanduser(workdir)
        if os.path.isdir(workdir):
            checks.append(("Working directory exists", True, workdir))
        else:
            checks.append(
                ("Working directory exists", False, f"{workdir} - directory not found")
            )

    # Check 3: goal or goals-file
    has_goal = bool(env.get("INFINITE_LOOP_GOAL", ""))
    has_goals_file = bool(env.get("INFINITE_LOOP_GOALS_FILE", ""))
    if has_goal or has_goals_file:
        src = "goal" if has_goal else "goals-file"
        checks.append(("Task definition", True, f"via --{src}"))
    else:
        checks.append(
            ("Task definition", None, "No goal set - pass --goal or --goals-file")
        )

    # Check 4: git repo (if --git is enabled)
    use_git = env.get("INFINITE_LOOP_GIT", "").lower() == "true"
    if use_git:
        import subprocess

        try:
            result = subprocess.run(
                ["git", "rev-parse", "--is-inside-work-tree"],
                capture_output=True,
                text=True,
                timeout=5,
            )
            if result.returncode == 0:
                checks.append(
                    ("Git repository (--git enabled)", True, "Inside a git repo")
                )
            else:
                checks.append(
                    (
                        "Git repository (--git enabled)",
                        False,
                        "Not inside a git repository",
                    )
                )
        except FileNotFoundError:
            checks.append(
                (
                    "Git repository (--git enabled)",
                    False,
                    "git binary not found on PATH",
                )
            )

    # Print results
    for desc, passed, details in checks:
        if passed is True:
            icon = "\033[32m\u2713\033[0m"  # green check
        elif passed is False:
            icon = "\033[31m\u2717\033[0m"  # red cross
        else:
            icon = "\033[33m?\033[0m"  # yellow question mark
        print(f"  {icon}  {desc}")
        indent = " " * 6
        if details:
            max_d = 72
            detail = details if len(details) <= max_d else details[: max_d - 3] + "..."
            print(f"{indent}{detail}")
    print()

    # Summary
    passed = sum(1 for _, p, _ in checks if p is True)
    warned = sum(1 for _, p, _ in checks if p is None)
    failed = sum(1 for _, p, _ in checks if p is False)
    total = len(checks)
    if failed == 0 and warned == 0:
        print(f"  \033[32mAll {total} checks passed\033[0m - ready to run!")
    elif failed == 0:
        print(f"  \033[33m{passed} passed, {warned} warnings\033[0m - can still run")
    else:
        print(
            f"  \033[31m{failed} failed, {warned} warnings, {passed} passed"
            f"\033[0m - fix issues before running"
        )
    print()


def main() -> None:
    """Entry point for `hermes_loop --init`."""
    run_wizard()
    sys.exit(0)


if __name__ == "__main__":
    main()
